---
title: "Hadoop install for Mac (单机／伪分布式配置)"
author: "Yanwei Song"
date: "3/24/2017"
output: 
  html_document:
    toc: yes
---

参考：

* http://rockyfeng.me/hadoop_single_node_cluster_mac.html
* http://haojunsui.github.io/2016/06/21/hadoop-single/
* https://github.com/100steps/Blogs/issues/10
* https://geekatwork.wordpress.com/2016/04/28/install-hadoop-and-spark-on-a-mac/


#一· 预装环境配置
##1. Homebrew

在terminal预先安装Homebrew

##2. java
检查电脑上java的版本

```
java -version
```

##Xcode (optional)

下载

#二· 配置ssh

为了保证远程登录管理 Hadoop 及 Hadoop 节点用户共享的安全性，Hadoop 需要配置使用 SSH 协议。

##1. Go to System Preferences -> Sharing -> check "Remote Login"

##2. Generate SSH keys
```
$ ssh-keygen -t rsa -P ""
$ cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
```
Another method: check the workflow on blackboard - bioinfor method1

##3. test
```
ssh localhost
```

show:
```
Last login: xxxxxxxx
```
显示时间信息，即配置完成。

#三· 安装及配置hadoop
##1. hadoop install
terminal :
```
brew install hadoop
```

if successful donwloaded, will show:
```
==> Downloading https://www.apache.org/dyn/closer.cgi?path=hadoop/common/hadoop-
==> Best Mirror http://mirror.bit.edu.cn/apache/hadoop/common/hadoop-2.7.2/hadoop-
######################################################################## 100.0%
==> Caveats
In Hadoop's config file:
/usr/local/Cellar/hadoop/2.7.2/libexec/etc/hadoop/hadoop-env.sh,
/usr/local/Cellar/hadoop/2.7.2/libexec/etc/hadoop/mapred-env.sh and
/usr/local/Cellar/hadoop/2.7.2/libexec/etc/hadoop/yarn-env.sh
$JAVA_HOME has been set to be the output of:
/usr/libexec/java_home
==> Summary
?  /usr/local/Cellar/hadoop/2.7.2: 6,304 files, 309.8M, built in 2 minutes 43 seconds
```

##2. Setting up a single node cluster
Change file as the following link shows:
https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html

##3. start Hadoop services:
Format HDFS
```
$ /usr/local/Cellar/hadoop/2.7.2
$ bin/hdfs namenode -format
```
If perform successful, we will see the following promot "successfully formatted" and "Exitting with status 0", if we see "Exitting with status 1", it is something wrong. 

If we see following error :
```
Error: JAVA_HOME is not set and could not be found.
```
which means there are something wrong with JAVA_HOME, we need to set JAVA_HOME first. 

Start hdfs
```
$ sbin/start-dfs.sh
```
Start yarn (MapReduce)
```
$ sbin/start-yarn.sh
```
Check start situation
```
jps
```
shows:
```
6467 Jps
5991 DataNode
6343 NodeManager
6106 SecondaryNameNode
6251 ResourceManager
5901 NameNode
```
If we start successfully, we will see "NameNode", "DataNode", and "SecondaryNameNode". If SecondaryNameNode not shows, we need run sbin/stop-dfs.sh to stop the process, and try to start again. If NameNode not show, which means configuration unsuccessfully. Go through the previous steps, and find problem. 


Stop hadoop:
```
./sbin/stop-dfs.sh
```

After configurate hadoop, when start hadoop next time, only have to run ```./sbin/start-dfs.sh```. 

##4. Validation
Check hdfs file directory
```
$ bin/hdfs dfs -ls /
```
If you don’t like to include the bin/ every time you run a hadoop command, you can do the following
```
$ vi ~/.bash_profile
```
append this line to the end of the file :
```
export PATH=$PATH:/usr/local/Cellar/hadoop/2.7.3/bin
```
```
$ source ~/.bash_profile
```
then, you can use the following commond line
```
$ hdfs dfs -ls/
```
Now try to add the following two folders in HDFS that is needed for MapReduce job.
```
$ hdfs dfs -mkdir /user
$ hdfs dfs -mkdir /user/{your username}
```
You can also open a browser and access Hadoop by using the following URL
http://localhost:50070/



##5. others
Method to solve error:
```
Could not find or load main class org.apache.hadoop.hdfs.server.namenode.Namenode
```
Add following env variables to ```~/.bash_profile```.

```
export HADOOP_HOME=/usr/local/Cellar/hadoop/2.7.3
export HADOOP_PREFIX=$HADOOP_HOME/libexec
export HADOOP_MAPRED_HOME=$HADOOP_PREFIX
export HADOOP_COMMON_HOME=$HADOOP_PREFIX
export HADOOP_HDFS_HOME=$HADOOP_PREFIX
export YARN_HOME=$HADOOP_PREFIX
```
source the changed file
```
source ~/.bash_profile
```

